# Generated by Django 5.0.2 on 2024-08-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='is_linkedin_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_twitter_connected',
            field=models.BooleanField(default=False),
        ),
    ]
