# Generated by Django 5.0.2 on 2024-09-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_user_following_list_user_is_linkedin_connected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following_list',
            new_name='user_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_linkedin_connected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_twitter_connected',
        ),
    ]
