# Generated by Django 5.0.2 on 2024-08-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scrapper_name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('scrapper_category', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('max_results', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
