# Generated by Django 5.0.2 on 2024-08-31 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapperlog',
            old_name='date',
            new_name='scrap_date',
        ),
    ]
