# Generated by Django 5.0.2 on 2024-08-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0002_rename_date_scrapperlog_scrap_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapperlog',
            name='keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapperlog',
            name='max_results',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapperlog',
            name='scrapper_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
