# Generated by Django 5.0.2 on 2024-09-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0004_platformcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platformcategory',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
