# Generated by Django 5.0.2 on 2024-09-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0005_rename_category_name_platformcategory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('profile_avatar', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
