# Generated by Django 5.0.2 on 2024-09-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0007_authorprofile_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
