# Generated by Django 5.0.2 on 2024-09-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0005_rename_category_name_platformcategory_name_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True, null=True)),
                ('post_source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('post_source_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('post_source_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('producthunt', 'Product Hunt'), ('bioarxiv', 'bioarxiv'), ('arxiv', 'arXiv'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=255, null=True)),
                ('total_activity', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.JSONField(blank=True, null=True)),
                ('ai_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('scrapper_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_scrapper.scrapperlog')),
            ],
        ),
    ]
