# Generated by Django 5.0.2 on 2024-08-31 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='source_url',
            new_name='post_source_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='post_source_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 8, 31)),
        ),
        migrations.AddField(
            model_name='post',
            name='post_source_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
