# Generated by Django 5.0.2 on 2024-08-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_source_url_post_post_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_source_date',
            field=models.DateField(blank=True),
        ),
    ]
