# Generated by Django 5.0.2 on 2024-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_promptlog_postsocial_total_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('producthunt', 'Product Hunt'), ('bioarxiv', 'bioarxiv'), ('arxiv', 'arXiv'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='platform',
            field=models.CharField(blank=True, choices=[('producthunt', 'Product Hunt'), ('bioarxiv', 'bioarxiv'), ('arxiv', 'arXiv'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postsocial',
            name='platform',
            field=models.CharField(blank=True, choices=[('producthunt', 'Product Hunt'), ('bioarxiv', 'bioarxiv'), ('arxiv', 'arXiv'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=255, null=True),
        ),
    ]
