# Generated by Django 5.0.2 on 2024-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_platformcategory_alter_postcontent_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcategory',
            name='category_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformcategory',
            name='platform',
            field=models.CharField(blank=True, choices=[('producthunt', 'Product Hunt'), ('bioarxiv', 'bioarxiv'), ('arxiv', 'arXiv'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('hackernews', 'Hacker News')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='platform',
            field=models.CharField(blank=True, choices=[('producthunt', 'Product Hunt'), ('bioarxiv', 'bioarxiv'), ('arxiv', 'arXiv'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('hackernews', 'Hacker News')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postsocial',
            name='platform',
            field=models.CharField(blank=True, choices=[('producthunt', 'Product Hunt'), ('bioarxiv', 'bioarxiv'), ('arxiv', 'arXiv'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('hackernews', 'Hacker News')], max_length=255, null=True),
        ),
    ]
