# Generated by Django 5.0.2 on 2024-09-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postsocial_author_postsocialsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='author',
        ),
    ]
