# Generated by Django 5.0.2 on 2024-08-31 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_post_source_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='scrapper_log',
            new_name='scrapper_log_id',
        ),
    ]
