# Generated by Django 5.0.2 on 2024-08-31 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0003_alter_scrapperlog_keyword_and_more'),
        ('posts', '0004_rename_scrapper_log_post_scrapper_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scrapper_log_id',
        ),
        migrations.AddField(
            model_name='post',
            name='scrapper_log',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='platform_scrapper.scrapperlog'),
            preserve_default=False,
        ),
    ]
