# Generated by Django 5.0.2 on 2024-09-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_postcontent_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
