# Generated by Django 5.0.2 on 2024-08-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_ai_summary_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
