# Generated by Django 5.0.2 on 2024-08-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0003_alter_scrapperlog_keyword_and_more'),
        ('posts', '0008_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('post_source_url', models.URLField(blank=True, null=True)),
                ('post_source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('post_source_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PostContent',
        ),
    ]
