# Generated by Django 5.0.2 on 2024-08-31 20:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postsocial_rename_post_postcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 31, 19, 58, 0, 109368))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 8, 31, 19, 58, 0, 109379))),
            ],
        ),
        migrations.AddField(
            model_name='postsocial',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 31)),
        ),
        migrations.AddField(
            model_name='postsocial',
            name='updated_at',
            field=models.DateField(default=datetime.date(2024, 8, 31)),
        ),
        migrations.AlterField(
            model_name='postsocial',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.profilesocial'),
        ),
    ]
