# Generated by Django 5.0.2 on 2024-08-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_profilesocial_postsocial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsocial',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postsocial',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilesocial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilesocial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
