# Generated by Django 5.0.2 on 2024-08-31 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_scrapper', '0003_alter_scrapperlog_keyword_and_more'),
        ('posts', '0011_alter_postsocial_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsocial',
            name='scrapper_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_scrapper.scrapperlog'),
        ),
    ]
